# Python 기초 문법

In [2]:
# hello world 주석

'''
주석 블럭
마크다운은 작은따옴표가 아니라 물결표 아래있는 작은 쉼표
'''
def helloworld():
  print('hello world')

helloworld()

hello world


Python에서는 들여쓰기가 중요  
공백(Space)이나 Tab을 이용하여 구분  

## 1. 반복/제어 정의 범위

In [3]:
print('start')
for i in range(10):
  if i>5:
    print('i = %d > 5' % i)
    # if의 들여쓰기 범위는 여기까지
  elif i<5:
    print('i = %d < 5' % i)
  else:
    print('i = %d = 5' % i)
  #for의 범위는 여기까지
print('end')

start
i = 0 < 5
i = 1 < 5
i = 2 < 5
i = 3 < 5
i = 4 < 5
i = 5 = 5
i = 6 > 5
i = 7 > 5
i = 8 > 5
i = 9 > 5
end


## 2. 함수/클래스 정의 범위

In [4]:
def function1():
  print('function start')
  print('function end')
print('script start')
function1()
print('script end')

script start
function start
function end
script end


# 입출력 (I/O) 하기


## 1. 입력 받기 : **input()** 화면을 통해 키보드로 입력을 받아 변수에 저장  

In [6]:
a = input()
print(a)

4
4


## 2. 출력 하기 : **print()** 원하는 내용을 화면을 통해 출력

* 표현식에 변수에 따라 달라질 내용은 변수형에 따라 다르게 표현
  1. %d(정수)
  2. %f(실수)
  3. %s(문자열)

In [12]:
i = 4
j = 4.5
k = 'abc'
print('i=%d j=%.1f k=%s'% (i,j,k))

i=4 j=4.5 k=abc


# Data를 묶음으로 처리하기

## 리스트 (List)

* 리스트 : [] 기호로 표현, 여러 데이터를 1열로 세워 묶음


In [14]:
list_mixed = [0, 2.5, 'abc']

In [16]:
# 비어있는 리스트 생성
empty_list = []
print(empty_list)

[]


In [18]:
# 직접 입력해서 생성

list_manual = [0, 1, 2, 3, 4]
print(list_manual)

[0, 1, 2, 3, 4]


In [22]:
# range 함수를 이용한 생성 (이하 A, B, C 모두 정수)
# range(B) - 0부터 1의 간격으로 B 보다 작은 정수까지 리스트 생성

list_new = list(range(10))
print(list_new)

# range(A,B) - A부터 시작해 1의 간격으로 B보다 작은 정수까지 리스트 생성

list_new = list(range(1,10))
print(list_new)

# range(A,B,C) - A부터 시작해 C의 간격으로 B보다 작은 정수까지 리스트 생성 (C가 음수일 경우 반대)

list_new = list(range(2,10,2))
print(list_new)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[]


In [ ]:
# 리스트의 +, *

list_manual = list(range(5))
list_new = list(range(4,-1,-1))
print(list_manual+list_new)
print(list_manual*2)

# 리스트의 행 벡터를 단순히 붙이거나 곱함 -> 반복을 함

In [31]:
# 리스트의 다양한 부가함수

# List의 마지막 열에 원소 추가 (리스트명).append(넣을 원소)
# range로 생성된 리스트에는 추가 불가능

list_manual = [0,1,2,3,4]
list_manual.append(5)
print(list_manual)

[0, 1, 2, 3, 4, 5]


In [32]:
# List의 원하는 위치에 원소 추가하기
# insert(위치,값) 참고로 시작위치의 값은 0 <-> MATLAB은 1부터

list_manual.insert(2,10)
print(list_manual)

[0, 1, 10, 2, 3, 4, 5]


In [33]:
# List의 맨 뒤에 원소 제거하기

list_manual.pop()
print(list_manual)

[0, 1, 10, 2, 3, 4]


In [34]:
# List의 원하는 위치에 원소 제거하기
# pop(위치)

list_manual.pop(2)
print(list_manual)

[0, 1, 2, 3, 4]


In [35]:
# List의 원소 개수 세기

num_data = len(list_manual)
print(num_data)

5


In [38]:
# List의 원소 위치 찾기 (처음으로 발견된 원소의 위치 반환)

position = list_manual.index(2)
print(position)

2


In [39]:
# List 크기순으로 정렬하기 (기본 오름차순)

list_manual.sort()
print(list_manual)
list_manual.sort(reverse=True)
print(list_manual)

[0, 1, 2, 3, 4]
[4, 3, 2, 1, 0]


In [40]:
# 원하는 부위 잘라내기 (슬라이싱)
# 하나만 선택해 반환하기

print(list_manual[2])

2


In [41]:
# [A:B] A위치부터, B보다 '작은'위치까지 선택
# [2:4] 2, 3의 위치 선택

print(list_manual[2:4])

[2, 1]


In [42]:
# [A:] 위치부터, 끝까지
# [:B] 시작부터, B보다 '작은'위치까지 선택

print(list_manual[2:])
print(list_manual[:4])

[2, 1, 0]
[4, 3, 2, 1]


In [ ]:
# [-A] 맨 뒤에서 부터 A번쨰

print(list_manual[-2])

# 튜플(Tuple)

## 튜플 : () 기호로 표현 , List와 비슷하지만 **수정불가**

* 수정이 불가하다는 것만 빼면 나머지 부가 함수들은 리스트와 거의 같다.

In [44]:
# 직접 입력해서 생성

tuple_manual = (0,1,2,3,4)
print(tuple_manual)

(0, 1, 2, 3, 4)


In [45]:
# range 함수를 이용한 생성 (이하 A, B, C 모두 정수)

print(tuple(range(2,10,2)))

(2, 4, 6, 8)


In [49]:
len(tuple_manual)

(1, 2, 3, 4)

In [50]:
tuple_manual.index(4)

4

In [51]:
tuple_manual[1:]

(1, 2, 3, 4)

# 세트[집합] (Set)

## 세트 : {} 기호로 표현, List와 비슷하지만 원소 중복 불가

In [52]:
empty_set ={}
print(empty_set)

{}


In [53]:
# 직접 입력해서 생성 - 중복원소는 제거된다.
set_manual = {0,1,2,3,4,4,3,2,1,0}
print(set_manual)

{0, 1, 2, 3, 4}


In [54]:
# range 함수를 이용한 생성 (이하 A, B, C 모두 정수)
print(set(range(2,10,2)))

{8, 2, 4, 6}


* 집합 관련 연산기능 추가로 제공

In [55]:
# 교집합 '&'

set_first = {1,3,5}
set_second = {1,2,4,8}

print(set_first & set_second)

{1}


In [57]:
# 합집합 '|'

print(set_first | set_second)

{1, 2, 3, 4, 5, 8}


In [58]:
# 차집합 '-'

print(set_first-set_second)

{3, 5}


In [59]:
# 부분집합 여부 확인
# A.issuperset(B) - B가 A의 부분집합인지 여부 (A가 B를 포함하는지 여부)

set_third = {1,3,5,7}
set_third.issuperset(set_first)

True

In [60]:
# 원소 여부 확인

3 in set_first

True

# 딕셔너리 (Dictionary)

## 딕셔너리 : {} 기호로 표현 (세트와 같음) 'key:value' 의 형태로 저장

In [69]:
my_dictionary = {'name':['John','Seyuni','Minhyeok'],'age':15,'height':1.76}
print(my_dictionary)

{'name': ['John', 'Seyuni', 'Minhyeok'], 'age': 15, 'height': 1.76}


* 선택시 위치 (정수, index)가 아닌 key를 이용

In [77]:
my_dictionary['name'][0]

'John'

In [79]:
# 딕셔너리가 리스트의 원소가 될수 있고 그 반대도 가능
first_user = {'name':'John','age':15,'height':1.76,'position':[15,3]} # 포지션의 경우 리스트 생성하여 딕셔너리의 원소로 들어감
second_user = {'name':'paul','age':17,'height':1.88,'position':[-2,7]}
users = [first_user,second_user] # 유저라는 리스트의 딕셔너리가 추가됨
print(users[0]['position'][0])

15


# 기본 수학 연산

* 변수(variable) : 어떤 데이터를 저장하는 공간


In [81]:
# 변수의 좋은 예

pos_x = 10
num_values = 5
_event_flag = False

# 변수의 나쁜 예

abc = 4
a1 = 50
xxxx = 3.4
temp1 = 4
temp2 = 5

# 데이터 타입 : 정수, 실수, bool, 문자열 등 python이 자동으로 관리

# 정수

number =5

# 실수

value = 2.5

# boolean

is_number = True

# 문자열 (string)

name = 'Ivan'

# 정수가 실수로 바뀌는 경우

number /= 2
print('number =', number)

number = 2.5


In [82]:
a = 10
b = 2.5

print(a+b, a-b, a*b, a/b, a//b, a%b, a**b) # // 몫 ** 제곱
print(a>b, a>=b, a<b, a<=b, a==b, a!=b, a>b or a<=b, a>b and a<=b)

12.5 7.5 25.0 4.0 4.0 0.0 316.22776601683796
True True False False False True True False


In [83]:
# numpy 활용 (numpy 라이브러리 활용법은 나중에 좀 더 자세히 다룰 예정입니다.)

import numpy as np

angle = np.pi/4
print(angle)
print(np.sin(angle))
print(np.cos(angle))
print(np.exp(angle))
print(np.round(angle))
print(np.ceil(angle))
print(np.floor(angle))

0.7853981633974483
0.7071067811865475
0.7071067811865476
2.1932800507380152
1.0
1.0
0.0


In [85]:
# 단순 반복 계산

'''
for 변수 in 리스트:
  수행문
'''
for i in [4,'text',1.5,True,{'name':'Charles','age':15}]:
  print(i)

'''
for 변수 in range(반복횟수):
  수행문
'''

for i in range(5):
  print(i)


4
text
1.5
True
{'name': 'Charles', 'age': 15}
0
1
2
3
4


In [86]:
# Continue / Break

for i in range(5):
  if i == 3:
    continue
  print(i)

0
1
2
4


In [87]:
for i in range(5):
  if i == 3:
    break
  for j in range(5):
    if j == 2:
      break
    print(i,j)

0 0
0 1
1 0
1 1
2 0
2 1


In [88]:
# 조건 반복 계산
# while : 조건을 만족하는 동안 반복

'''
while(조건):
  수행문
'''

i = [1,2,3,4,-1,5,6,7,8]
j = []
count = 0
while(i[count]>0):
  j.append(i[count])
  count += 1
print(j)

[1, 2, 3, 4]


In [90]:
# for / while 활요 예제

for i in range(2,5):
  for j in range(1,10):
    print('%d * %d = %d'%(i,j,i*j))
  print('--------------')

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
--------------
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
--------------
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
--------------


In [91]:
# 프로그램 동작에 관한 정보를 제공한다.
print('원하는 단수를 입력하시고, 종료하려면 -1을 입력하세요.')

# 의도적으로 무한루프를 활용한다.
while(True):

  # 사용자가 정수를 입력해준다고 가정한다.
  i = int(input())

  # -1을 입력시 반복문을 탈출한다.
  if i == -1:
    break

  #출력

  for j in range(1,10):
    print('%d x %d = %d'%(i,j,i*j))

원하는 단수를 입력하시고, 종료하려면 -1을 입력하세요.
1
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
13
13 x 1 = 13
13 x 2 = 26
13 x 3 = 39
13 x 4 = 52
13 x 5 = 65
13 x 6 = 78
13 x 7 = 91
13 x 8 = 104
13 x 9 = 117
5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
-1


# 조건문

## if : 조건을 만족할 때 원하는 기능 수행

In [ ]:
'''
if (조건):
  수행문
elif (조건):
  수행문
else:
  수행문
'''



# 행렬선언

## 특수행렬 : 1행렬, 0행렬, 단위 행렬(Identity Matrix)

## 일반 행렬 : 데이터형 변경(astype)

In [92]:
# 3x2 형태의 1행렬 선언
# Input으로 tuple을 받는것에 주의!

one_matrix = np.ones((3,2))
print(one_matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [93]:
# 3x2 형태의 0행렬 선언

zero_matrix = np.zeros((3,2))
print(zero_matrix)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [94]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [97]:
# 일반 행렬 : 원소 직접입력 (리스트 이용)

data_int = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data_int)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [98]:
# Matrix 형태 출력
print(data_int.shape)

(3, 3)


In [99]:
# 원소의 데이터형 출력

print(data_int.dtype)

int64


In [100]:
# 데이터형 변경 (astype)
# int -> np.int64
# float -> np.float64

data_float = data_int.astype(np.float64)
print(data_float)
print(data_float.dtype)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
float64


# 행렬 연산

## 사칙 연산: 요소별 (element-wise) 연산


In [101]:
# 요소별 곱셈

print(data_int * data_int)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [102]:
# 상수 덧셈

print(data_int + 3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [103]:
# 상수 나눗셈

print(data_int /3)

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [104]:
# Transpose 연산 (전치행렬)

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,0,-1],[1,1,0]])
print(x)
print(y)
print(y.T)

[[1 2 3]
 [4 5 6]]
[[ 1  0 -1]
 [ 1  1  0]]
[[ 1  1]
 [ 0  1]
 [-1  0]]


In [105]:
# 행렬 곱 연산

print(np.dot(x,y.T))

[[-2  3]
 [-2  9]]


In [106]:
# 선택 및 수정 -> 결국 행렬도 리스트이기 때문에

# 연속 정수로 array 생성

data_range = np.arange(10) #행렬 선언은 arange를 사용해야함
print(data_range)

[0 1 2 3 4 5 6 7 8 9]


In [109]:
# index를 이용한 선택

print(data_range[0])

0


In [110]:
# slicing

print(data_range[1:4])

[1 2 3]


In [111]:
# slicing을 이용한 수정
data_range[1:4]=10
print(data_range)

[ 0 10 10 10  4  5  6  7  8  9]


In [112]:
# slicing을 하면 주소 (pointer)가 반환됨에 주의!
tmp =data_range[1:4]
tmp[1]=20
print(data_range)

# 변수에 담겨있는 데이터가 아닌 주소를 반환하기 때문에 원본 값이 변동됨

[ 0 10 20 10  4  5  6  7  8  9]


In [116]:
# 2차원 이상의 경우도 유사하다.

print(data_int[2])
print(data_int[:2])
print(data_int[2][0])
print(data_int[2,0])
print(data_int[:2,1:])
data_int[:2,1:]=0
print(data_int)

[7 8 9]
[[1 2 3]
 [4 5 6]]
7
7
[[2 3]
 [5 6]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]


In [117]:
# 역행렬

import numpy.linalg as lin
mat = np.array([[2,2,0],[-2,1,1],[3,0,1]])
print(lin.inv(mat))

[[ 0.08333333 -0.16666667  0.16666667]
 [ 0.41666667  0.16666667 -0.16666667]
 [-0.25        0.5         0.5       ]]


In [118]:
# 행렬식

print(lin.det(mat))

12.0


In [119]:
# 행렬 방정식

matA = np.array([[3,2,1],[1,-1,3],[5,4,-2]])
matB = np.array([7,3,1])

print(lin.solve(matA,matB))

[-3.  6.  4.]


1시간 14분 15초 그래프부터 이어서